### ISSUE TITLE
Readme unclear

### ISSUE THREAD

**Issue by ant-t** [ag91/EasyOrgEnsime#2]
Hi,

The readme is not very clear on what to do. 

What does it mean to evaluate the easy-org-ensime.el file? Do I put it in the .emacs directory, evaluate it line by line?

What how to evaluate (eoe-run)?

Where are async.el, sbt, sbt-ensime plugin, and ensime provided from?

I can't get anywhere with this currently, but love the idea of getting back the functionality that was lost for literate programming in scala and org-mode.

**Comment by ag91** [comment]
Hi there,

Thanks for the feedback. I wrote this mode for people more or less experienced with Emacs and Ensime.
Evaluating a file in emacs can be done in multiple ways: `(load-file "easy-org-ensime.el")` in your init should do.
`eoe-run ` can be done with `M-x eoe-run` as the function is marked as interactive.
async.el is a dependency of this mode and can be installed with M-x package-install async 
sbt, sbt-ensime plugin, and ensime are expected to be known, but you are right we can add some reference for completeness.

**Comment by ag91** [comment]
Forgot to close this. Thanks again
